// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// mycppsum
double mycppsum(const Eigen::VectorXd& invec);
RcppExport SEXP _LogisticFAR_mycppsum(SEXP invecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type invec(invecSEXP);
    rcpp_result_gen = Rcpp::wrap(mycppsum(invec));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_LogisticFAR_mycppsum", (DL_FUNC) &_LogisticFAR_mycppsum, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_LogisticFAR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
