# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Logistic_FAR_FLiRTI_Solver_Core <- function(y_vec, x_mat, h, kn, p, p_type, p_param, mu2, a, bj_vec, cj_vec, rj_vec, weight_vec, tol, max_iter, relax_vec, hd_mat, hd_inv, delta_init, eta_stack_init, mu1_init) {
    .Call(`_LogisticFAR_Logistic_FAR_FLiRTI_Solver_Core`, y_vec, x_mat, h, kn, p, p_type, p_param, mu2, a, bj_vec, cj_vec, rj_vec, weight_vec, tol, max_iter, relax_vec, hd_mat, hd_inv, delta_init, eta_stack_init, mu1_init)
}

Logistic_FAR_Ortho_Solver_Core <- function(y_vec, x_mat, h, kn, p, p_type, p_param, mu2, a, bj_vec, cj_vec, rj_vec, weight_vec, tol, max_iter, relax_vec, t_mat_stack, svd_vec_stack, start_id_vec, hd_mat, hd_inv, delta_init, eta_stack_init, mu1_init) {
    .Call(`_LogisticFAR_Logistic_FAR_Ortho_Solver_Core`, y_vec, x_mat, h, kn, p, p_type, p_param, mu2, a, bj_vec, cj_vec, rj_vec, weight_vec, tol, max_iter, relax_vec, t_mat_stack, svd_vec_stack, start_id_vec, hd_mat, hd_inv, delta_init, eta_stack_init, mu1_init)
}

Logistic_FAR_Solver_Core <- function(y_vec, x_mat, h, kn, p, p_type, p_param, mu2, a, bj_vec, cj_vec, rj_vec, weight_vec, tol, max_iter, relax_vec, hd_mat, hd_inv, delta_init, eta_stack_init, mu1_init) {
    .Call(`_LogisticFAR_Logistic_FAR_Solver_Core`, y_vec, x_mat, h, kn, p, p_type, p_param, mu2, a, bj_vec, cj_vec, rj_vec, weight_vec, tol, max_iter, relax_vec, hd_mat, hd_inv, delta_init, eta_stack_init, mu1_init)
}

